-- MySQL Script generated by MySQL Workbench
-- Thu Aug 30 10:45:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EstacionamientoSobreCalles
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `EstacionamientoSobreCalles` ;

-- -----------------------------------------------------
-- Schema EstacionamientoSobreCalles
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EstacionamientoSobreCalles` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `EstacionamientoSobreCalles` ;

-- -----------------------------------------------------
-- Table `TAB_COMMENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAB_COMMENTS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TAB_COMMENTS` (
  `ID_COMMENTS` BIGINT(50) NOT NULL,
  `DES_COMMENTS` VARCHAR(45) NOT NULL,
  `DATE_COMMENTS` VARCHAR(45) NOT NULL,
  `ACTIVE` VARCHAR(45) NOT NULL,
  `ID_USER` BIGINT(50) NOT NULL,
  PRIMARY KEY (`ID_COMMENTS`, `ID_USER`))
ENGINE = InnoDB
COMMENT = 'Se almacenaran los comentarios relacionados por los usuarios.';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TAB_IMAGES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAB_IMAGES` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TAB_IMAGES` (
  `ID_IMAGE` INT NOT NULL,
  `ID_USER` BIGINT(50) NOT NULL,
  `DES_IMAGEN` VARCHAR(45) NOT NULL,
  `DATE_IMAGEN` DATE NOT NULL,
  `ACTIVE` VARCHAR(45) NOT NULL,
  `ID_SIGNAL` BIGINT(50) NOT NULL,
  PRIMARY KEY (`ID_IMAGE`, `ID_USER`, `ID_SIGNAL`))
ENGINE = InnoDB
COMMENT = 'Se almacenaran las imagenes subidas por los usuarios.';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TAB_RANKING`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAB_RANKING` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TAB_RANKING` (
  `IDRANKING` BIGINT(50) NOT NULL,
  `ID_USER` BIGINT(50) NOT NULL,
  `TOP` VARCHAR(45) NOT NULL,
  `DATE_RANKING` DATE NOT NULL,
  PRIMARY KEY (`IDRANKING`))
ENGINE = InnoDB
COMMENT = 'Se almacenaran los usuarios con mejores calificaciones realizadas por los conductores o peatones.';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TAB_SIGNALS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAB_SIGNALS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TAB_SIGNALS` (
  `ID_SIGNAL` BIGINT(50) NOT NULL,
  `DES_SIGNAL` VARCHAR(45) NOT NULL,
  `ACTIVE` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_SIGNAL`))
ENGINE = InnoDB
COMMENT = 'Se almacenaran las señales de transito y sus descripciones';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TAB_USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAB_USUARIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TAB_USUARIO` (
  `ID_USER` BIGINT(50) NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `LASTNAME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `DATE_USER` DATE NOT NULL,
  `ACTIVE` VARCHAR(45) NOT NULL,
  `ID_RANKING` BIGINT(50) NOT NULL,
  PRIMARY KEY (`ID_USER`, `ID_RANKING`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
